const l = {
  r: {
    url: 'https://api.github.com/repos/btholt/complete-intro-to-react-v7/issues/6',
    repository_url: 'https://api.github.com/repos/btholt/complete-intro-to-react-v7',
    labels_url: 'https://api.github.com/repos/btholt/complete-intro-to-react-v7/issues/6/labels{/name}',
    comments_url: 'https://api.github.com/repos/btholt/complete-intro-to-react-v7/issues/6/comments',
    events_url: 'https://api.github.com/repos/btholt/complete-intro-to-react-v7/issues/6/events',
    html_url: 'https://github.com/btholt/complete-intro-to-react-v7/issues/6',
    id: 1165925102,
    node_id: 'I_kwDOGxk-MM5Ffpru',
    number: 6,
    title: 'redux-promise-middleware link is not working',
    user: {
      login: 'thesunilbagde',
      id: 6269292,
      node_id: 'MDQ6VXNlcjYyNjkyOTI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/6269292?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/thesunilbagde',
      html_url: 'https://github.com/thesunilbagde',
      followers_url: 'https://api.github.com/users/thesunilbagde/followers',
      following_url: 'https://api.github.com/users/thesunilbagde/following{/other_user}',
      gists_url: 'https://api.github.com/users/thesunilbagde/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/thesunilbagde/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/thesunilbagde/subscriptions',
      organizations_url: 'https://api.github.com/users/thesunilbagde/orgs',
      repos_url: 'https://api.github.com/users/thesunilbagde/repos',
      events_url: 'https://api.github.com/users/thesunilbagde/events{/privacy}',
      received_events_url: 'https://api.github.com/users/thesunilbagde/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2022-03-11T02:21:50Z',
    updated_at: '2022-03-11T02:24:09Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body:
      'should be \r\n' +
      'https://pburtchaell.gitbook.io/redux-promise-middleware/\r\n' +
      'Site section below \r\n' +
      'https://btholt.github.io/complete-intro-to-react-v7/lessons/redux/action-creators\r\n' +
      '<img width="745" alt="Screenshot 2022-03-11 at 7 53 34 AM" src="https://user-images.githubusercontent.com/6269292/157790032-0deda407-fa13-4ded-9df4-451b2e9684e4.png">\r\n' +
      '\r\n' +
      '<img width="1234" alt="Screenshot 2022-03-11 at 7 52 09 AM" src="https://user-images.githubusercontent.com/6269292/157789892-9cadf54d-a320-4593-bcc9-03435db034e6.png">\r\n',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/btholt/complete-intro-to-react-v7/issues/6/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url: 'https://api.github.com/repos/btholt/complete-intro-to-react-v7/issues/6/timeline',
    performed_via_github_app: null,
    state_reason: null,
  },
};
